"use strict";
exports.__esModule = true;
var library_1 = require("./library");
var book_1 = require("./book");
var libro1 = new book_1.Book("Introducción a Javascript", 233, "2344433-BC23333", "Joseph Smith", "Now Editions");
var libro2 = new book_1.Book("Introducción a Typescript", 233, "2344433-BC23333", "Joseph Smith", "Now Editions");
var libreria1 = new library_1.Library([libro1, libro2], "hola dirección", "los manejamos");
console.log(libreria1.toString());
console.log(libreria1.getNumberOfBooks());
console.log((libreria1.findByAuthor("Joseph Smith")));
